// Generated by gencpp from file local_planner_student/localGoalResponse.msg
// DO NOT EDIT!


#ifndef LOCAL_PLANNER_STUDENT_MESSAGE_LOCALGOALRESPONSE_H
#define LOCAL_PLANNER_STUDENT_MESSAGE_LOCALGOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace local_planner_student
{
template <class ContainerAllocator>
struct localGoalResponse_
{
  typedef localGoalResponse_<ContainerAllocator> Type;

  localGoalResponse_()
    : possible()  {
    }
  localGoalResponse_(const ContainerAllocator& _alloc)
    : possible(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _possible_type;
  _possible_type possible;





  typedef boost::shared_ptr< ::local_planner_student::localGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_planner_student::localGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct localGoalResponse_

typedef ::local_planner_student::localGoalResponse_<std::allocator<void> > localGoalResponse;

typedef boost::shared_ptr< ::local_planner_student::localGoalResponse > localGoalResponsePtr;
typedef boost::shared_ptr< ::local_planner_student::localGoalResponse const> localGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_planner_student::localGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_planner_student::localGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_planner_student::localGoalResponse_<ContainerAllocator1> & lhs, const ::local_planner_student::localGoalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.possible == rhs.possible;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_planner_student::localGoalResponse_<ContainerAllocator1> & lhs, const ::local_planner_student::localGoalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_planner_student

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_planner_student::localGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_planner_student::localGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_planner_student::localGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dc6b33d34665b2258d9dcbce54cc288";
  }

  static const char* value(const ::local_planner_student::localGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dc6b33d34665b22ULL;
  static const uint64_t static_value2 = 0x58d9dcbce54cc288ULL;
};

template<class ContainerAllocator>
struct DataType< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_planner_student/localGoalResponse";
  }

  static const char* value(const ::local_planner_student::localGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool possible\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::local_planner_student::localGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.possible);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct localGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_planner_student::localGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_planner_student::localGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "possible: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.possible);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_PLANNER_STUDENT_MESSAGE_LOCALGOALRESPONSE_H
