// Generated by gencpp from file local_planner_student/localGoal.msg
// DO NOT EDIT!


#ifndef LOCAL_PLANNER_STUDENT_MESSAGE_LOCALGOAL_H
#define LOCAL_PLANNER_STUDENT_MESSAGE_LOCALGOAL_H

#include <ros/service_traits.h>


#include <local_planner_student/localGoalRequest.h>
#include <local_planner_student/localGoalResponse.h>


namespace local_planner_student
{

struct localGoal
{

typedef localGoalRequest Request;
typedef localGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct localGoal
} // namespace local_planner_student


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::local_planner_student::localGoal > {
  static const char* value()
  {
    return "32b6639f4bc895cfbd706c1320b329cd";
  }

  static const char* value(const ::local_planner_student::localGoal&) { return value(); }
};

template<>
struct DataType< ::local_planner_student::localGoal > {
  static const char* value()
  {
    return "local_planner_student/localGoal";
  }

  static const char* value(const ::local_planner_student::localGoal&) { return value(); }
};


// service_traits::MD5Sum< ::local_planner_student::localGoalRequest> should match
// service_traits::MD5Sum< ::local_planner_student::localGoal >
template<>
struct MD5Sum< ::local_planner_student::localGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::local_planner_student::localGoal >::value();
  }
  static const char* value(const ::local_planner_student::localGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_planner_student::localGoalRequest> should match
// service_traits::DataType< ::local_planner_student::localGoal >
template<>
struct DataType< ::local_planner_student::localGoalRequest>
{
  static const char* value()
  {
    return DataType< ::local_planner_student::localGoal >::value();
  }
  static const char* value(const ::local_planner_student::localGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::local_planner_student::localGoalResponse> should match
// service_traits::MD5Sum< ::local_planner_student::localGoal >
template<>
struct MD5Sum< ::local_planner_student::localGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::local_planner_student::localGoal >::value();
  }
  static const char* value(const ::local_planner_student::localGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_planner_student::localGoalResponse> should match
// service_traits::DataType< ::local_planner_student::localGoal >
template<>
struct DataType< ::local_planner_student::localGoalResponse>
{
  static const char* value()
  {
    return DataType< ::local_planner_student::localGoal >::value();
  }
  static const char* value(const ::local_planner_student::localGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCAL_PLANNER_STUDENT_MESSAGE_LOCALGOAL_H
