// Generated by gencpp from file local_planner_student/Path.msg
// DO NOT EDIT!


#ifndef LOCAL_PLANNER_STUDENT_MESSAGE_PATH_H
#define LOCAL_PLANNER_STUDENT_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <local_planner_student/PathRequest.h>
#include <local_planner_student/PathResponse.h>


namespace local_planner_student
{

struct Path
{

typedef PathRequest Request;
typedef PathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Path
} // namespace local_planner_student


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::local_planner_student::Path > {
  static const char* value()
  {
    return "7a70c4b6b34405650650e53c84f8e094";
  }

  static const char* value(const ::local_planner_student::Path&) { return value(); }
};

template<>
struct DataType< ::local_planner_student::Path > {
  static const char* value()
  {
    return "local_planner_student/Path";
  }

  static const char* value(const ::local_planner_student::Path&) { return value(); }
};


// service_traits::MD5Sum< ::local_planner_student::PathRequest> should match
// service_traits::MD5Sum< ::local_planner_student::Path >
template<>
struct MD5Sum< ::local_planner_student::PathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::local_planner_student::Path >::value();
  }
  static const char* value(const ::local_planner_student::PathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_planner_student::PathRequest> should match
// service_traits::DataType< ::local_planner_student::Path >
template<>
struct DataType< ::local_planner_student::PathRequest>
{
  static const char* value()
  {
    return DataType< ::local_planner_student::Path >::value();
  }
  static const char* value(const ::local_planner_student::PathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::local_planner_student::PathResponse> should match
// service_traits::MD5Sum< ::local_planner_student::Path >
template<>
struct MD5Sum< ::local_planner_student::PathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::local_planner_student::Path >::value();
  }
  static const char* value(const ::local_planner_student::PathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_planner_student::PathResponse> should match
// service_traits::DataType< ::local_planner_student::Path >
template<>
struct DataType< ::local_planner_student::PathResponse>
{
  static const char* value()
  {
    return DataType< ::local_planner_student::Path >::value();
  }
  static const char* value(const ::local_planner_student::PathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCAL_PLANNER_STUDENT_MESSAGE_PATH_H
